aliases:
    cdfleek: cd ~/.config/home-manager
bling: low
ejected: false
flakedir: .config/home-manager
git:
    autocommit: true
    autopull: true
    autopush: true
    enabled: true
name: My Fleek Configuration
packages:
    - helix
    - vim
    - pipx
    - vscode
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - starship
shell: bash
systems:
    - arch: x86_64
      hostname: exo
      os: linux
      username: jorge
unfree: true
