aliases:
    cdfleek: cd ~/.config/home-manager
bling: low
ejected: false
flakedir: .config/home-manager
name: My Fleek Configuration
packages:
    - helix
    - vim
    - ntopng
    - pipx
paths:
    - $HOME/bin
    - $HOME/.local/bin
programs:
    - dircolors
    - starship
repo: git@github.com:castrojo/homies
shell: bash
systems:
    - arch: x86_64
      git:
        email: jorge.castro@gmail.com
        name: Jorge O. Castro
      hostname: exo
      os: linux
      username: jorge
unfree: true
